name: swift
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.2.0=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - astroid=3.2.4=py312h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=23.1.0=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - black=24.8.0=py312h06a4308_0
  - black-jupyter=24.8.0=hd8ed1ab_1
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_0
  - cfgv=3.4.0=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py312h6a678d5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py312h06a4308_0
  - distlib=0.3.8=py312h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - gcc=14.2.0=h96c4ede_1
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx=14.2.0=h96c4ede_1
  - gxx_impl_linux-64=14.2.0=h2c03514_1
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - identify=2.5.5=py312h06a4308_0
  - idna=3.7=py312h06a4308_0
  - ipdb=0.13.13=pyhd8ed1ab_0
  - ipykernel=6.28.0=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - ipywidgets=8.1.2=py312h06a4308_0
  - isort=5.13.2=py312h06a4308_0
  - jedi=0.19.1=py312h06a4308_0
  - jinja2=3.1.4=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.0.0=py312h06a4308_9
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.2.5=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.10=py312h06a4308_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsanitizer=14.2.0=h2a3dede_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.2.0=h41c2201_101
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib-base=3.9.2=py312h66fe004_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - mypy_extensions=1.0.0=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nodeenv=1.7.0=py312h06a4308_0
  - notebook=7.2.2=py312h06a4308_1
  - notebook-shim=0.2.3=py312h06a4308_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.1=py312h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - pre-commit=3.4.0=py312h06a4308_1
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pylint=3.2.7=py312h06a4308_0
  - pyparsing=3.1.2=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.7=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.6.0=py312h06a4308_0
  - qtpy=2.4.1=py312h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.3=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rich=13.7.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - send2trash=1.8.2=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tokenize-rt=6.0.0=pyhd8ed1ab_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - ukkonen=1.0.1=py312hdb19cb5_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - virtualenv=20.26.1=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - widgetsnbextension=4.0.10=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - arrow==1.3.0
      - arxiv==2.1.3
      - attrdict==2.0.1
      - audioread==3.0.1
      - binpacking==1.5.2
      - bitsandbytes==0.44.1
      - blinker==1.8.2
      - brotli==1.1.0
      - cachetools==5.5.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==43.0.1
      - dacite==1.8.1
      - datasets==2.21.0
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.14.4
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - duckduckgo-search==5.3.1b1
      - editdistance==0.8.1
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - evalscope==0.5.4
      - evaluate==0.4.3
      - fastapi==0.115.0
      - feedparser==6.0.11
      - ffmpy==0.4.0
      - fire==0.7.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - func-timeout==4.3.5
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.44.1
      - gradio-client==1.3.0
      - griffe==1.3.2
      - grpcio==1.66.2
      - h2==4.1.0
      - h5py==3.12.1
      - hjson==3.1.0
      - hpack==4.0.0
      - huggingface-hub==0.25.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperframe==6.0.1
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - immutabledict==4.2.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inflate64==1.0.0
      - isoduration==20.11.0
      - jieba==0.42.1
      - jiter==0.6.1
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - kaldiio==2.18.0
      - lagent==0.2.3
      - lazy-loader==0.4
      - levenshtein==0.26.0
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - loralib==0.1.2
      - lxml==5.3.0
      - markdown==3.7
      - mmengine==0.10.5
      - mmengine-lite==0.10.5
      - modelscope==1.18.1
      - more-itertools==10.5.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - ms-opencompass==0.1.1
      - ms-vlmeval==0.0.9
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - narwhals==1.9.2
      - networkx==3.3
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - openai==1.51.2
      - opencc==1.1.9
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - optimum==1.23.3
      - orjson==3.10.7
      - oss2==2.19.0
      - pandas==2.2.3
      - peft==0.12.0
      - phx-class-registry==5.0.0
      - plotly==5.24.1
      - pooch==1.8.2
      - portalocker==2.10.1
      - prettytable==3.11.0
      - proglog==0.1.10
      - propcache==0.2.0
      - protobuf==5.28.2
      - py-cpuinfo==9.0.0
      - py7zr==0.22.0
      - pyarrow==17.0.0
      - pybcj==1.0.2
      - pycryptodome==3.21.0
      - pycryptodomex==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydeck==0.9.1
      - pydub==0.25.1
      - pympler==1.1
      - pypinyin==0.53.0
      - pyppmd==1.1.0
      - python-dotenv==1.0.1
      - python-levenshtein==0.26.0
      - python-multipart==0.0.12
      - pyzstd==0.16.2
      - rank-bm25==0.2.2
      - rapidfuzz==3.10.0
      - regex==2024.9.11
      - requests-toolbelt==1.0.0
      - rouge==1.0.1
      - rouge-chinese==1.0.3
      - rouge-score==0.1.2
      - ruff==0.6.9
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==3.1.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - setuptools==69.5.1
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - shtab==1.7.1
      - simple-ddl-parser==1.7.1
      - simplejson==3.19.3
      - slam-llm==0.0.1
      - smmap==5.0.1
      - socksio==1.0.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - starlette==0.38.6
      - streamlit==1.39.0
      - sty==1.0.6
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - timeout-decorator==0.5.0
      - tokenizers==0.20.0
      - tomli==2.0.2
      - tomlkit==0.12.0
      - torch==2.4.1
      - transformers==4.45.2
      - transformers-stream-generator==0.0.5
      - triton==3.0.0
      - trl==0.11.2
      - typer==0.12.5
      - types-python-dateutil==2.9.0.20241003
      - tyro==0.8.11
      - tzdata==2024.2
      - uri-template==1.3.0
      - uvicorn==0.31.0
      - validators==0.34.0
      - wandb==0.18.6
      - watchdog==5.0.3
      - webcolors==24.8.0
      - websockets==12.0
      - werkzeug==3.0.4
      - whisper==1.1.10
      - whisper-normalizer==0.0.10
      - xlsxwriter==3.2.0
      - xtuner==0.1.11
      - xxhash==3.5.0
      - yapf==0.40.2
      - yarl==1.14.0
      - zipp==3.20.2
